#########################--mysql--########################
spring:
    rabbitmq:
      host: 121.43.226.133
      port: 5672
      password: guest
      username: guest
      virtual-host: /
      listener:
        auto-startup: true
server:
  port: 8080
  display-name: "liubo-loan"
  tomcat:
    accesslog:
      directory: /opt/logs/
      prefix: acesslog
      suffix: .log
    uri-encoding: UTF-8
  context-path: /liubo-loan # 访问路径，比如 localhost:8080/liubo-loan

logging:
  file: ./springboot.log
  level: info

        # 使用druid数据源
#########################--mysql end--########################
